# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: format
        name: format
        entry: hatch fmt
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
      - id: types
        name: types
        entry: hatch run check-types
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
